name: 'Create Image'

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*.*.*"

jobs:
  create_image:
    name: Create Image
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static binfmt-support

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout pi-gen
        uses: actions/checkout@v4
        with:
          repository: RPI-Distro/pi-gen
          ref: arm64
          path: pi-gen

      - name: Setup pi-gen
        run: |
          install -m 755 "pianoberry/files/Pianoteq 8" pi-gen/pianoberry/files/usr/local/bin/
          ./setup.sh

      - name: Build
        run: |
          cd pi-gen
          ./build-docker.sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: pi-gen/deploy

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ !env.ACT && (startsWith(github.ref, 'refs/tags/')) }}
        with:
          files: |
            pi-gen/deploy/*.zip
